### ISSUE TITLE
Error: Schema could not be found

### ISSUE THREAD

**Issue by gllmhyt** [paysonwallach/spruce-paysonwallach.com#1]
When installing spruce, from extension's website or from git archive, I got the following error that makes me unable to use it: ```schema [...] could not be found```.

**Comment by gllmhyt** [comment]
OK, so, `org.gnome.shell.extensions.spruce.gschema.xml` is installed in `$HOME/.local/share/glib-2.0/schemas`. The other extension I have installed have their own folder for schemas and symlink it to `$HOME/.local/share/glib-2.0/schemas`. So I got around it with the following commands:

```bash
# Create the schemas folder in the extension's installation directory
mkdir -p $HOME/.local/share/gnome-shell/extensions/spruce@paysonwallach.com/schemas/
# Move the schema file to the schema folder in the extension's installation directory
mv $HOME/.local/share/glib-2.0/schemas/org.gnome.shell.extensions.spruce.gschema.xml $HOME/.local/share/gnome-shell/extensions/spruce@paysonwallach.com/schemas/
# Symlink the schema file to glib's schema directory
ln -s $HOME/.local/share/gnome-shell/extensions/spruce@paysonwallach.com/schemas/org.gnome.shell.extensions.spruce.gschema.xml $HOME/.local/share/glib-2.0/schemas/org.gnome.shell.extensions.spruce.gschema.xml
# Compile!
glib-compile-schemas $HOME/.local/share/gnome-shell/extensions/spruce@paysonwallach.com/schemas/
glib-compile-schemas $HOME/.local/share/glib-2.0/schemas/
```

**Comment by paysonwallach** [comment]
I'm sorry to hear that you were having an issue but I'm glad that you were able to resolve it. The latest version (Version 3 on GNOME Shell Extensions) does not seem to have this issue (Tested in a clean Ubuntu installation), however I've updated the build system per your observation that most other extensions keep their schemas in their source directory and removed the schema folder option for the time being (And probably won't add it back unless people ask for it, for simplicity). Out of curiosity, what version of GNOME Shell are you running?

**Comment by gllmhyt** [comment]
Thank you for your support, I will test it asap. I have gnome-shell 1:3.34.1+56+gbb24df2f9-1 (latest Arch Linux).
